// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function y(){function m(){var a=this.id;"menu0"===a?c("https://www.chromeactions.com/",1,"https://www.facebook.com/magicactions",0):"menu1"==a&&e(d.runtime.getURL("AZUK.html"))}function z(a){var b;b=parseInt((a.target.id?a.target:a.target.parentElement).id.slice(1));0==b?c("https://www.chromeactions.com/magic-actions-for-youtube-support.html",1,"https://www.facebook.com/magicactions",0):1==b?c("https://www.chromeactions.com/magic-actions-for-youtube-help-and-tips.html",1,"https://www.facebook.com/magicactions",
0):2==b?d.runtime.sendMessage('{"id":7}'):3==b?e("chrome://plugins"):4==b?e("https://www.youtube.com/my_history"):5==b?e("chrome://extensions"):6==b?c("https://www.hotcleaner.com/clickclean-app.html",1,"https://myaccount.google.com/intro/privacycheckup/1",0):7==b?e("https://www.facebook.com/magicactions"):8==b?e("https://www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1"):9==b?e("https://plus.google.com/110367533603365326399/posts"):10==b&&e("https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews");
a.stopPropagation()}function c(a,b,f,h){p(function(k){k?e(a,b):e(f,h)})}function e(a,b){function f(a){d.windows.update(a.windowId,{focused:!0})}d.tabs.query({url:a},function(h){if(h&&h.length)d.tabs.update(h[0].id,{active:!0},f);else if(b)try{d.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){d.runtime.lastError&&d.tabs.create({url:a,active:!0},f)})}catch(k){d.tabs.create({url:a,active:!0},f)}else d.tabs.create({url:a,active:!0},f)})}function p(a){y("HEAD","https://www.chromeactions.com/",
0,"text",function(b){console.log(b);!b||200!=b.code&&304!=b.code?a():a(1)})}function y(a,b,f,h,k){var d={code:0},l=new XMLHttpRequest;l.open(a,b,!0);h&&(l.responseType=h);l.onload=function(a){d.code=this.status||0;d.data=this.response;k(d)};l.onerror=function(){k(d)};l.onabort=function(){k(d)};l.send(f)}(function(){var a,b=w;a=document.createElement("link");a.rel="stylesheet";a.type="text/css";a.href="css/m.css";b.appendChild(a);a=d.i18n.getMessage("menu").split(";");var f=document.createDocumentFragment(),
h=document.createElement("div"),b=document.createElement("div"),k;h.id="menu";b.id="box";f.appendChild(h);f.appendChild(b);for(var c=0;c<a.length;c++)k=document.createElement("div"),k.className="nav",k.id="menu"+c,k.textContent=a[c],k.addEventListener("click",m,!1),h.appendChild(k);w.appendChild(f);h=w.querySelector("#box");f=[3,"dark","report.png",0,7,0,"help1.png",1,3,"dark","options.png",2,3,"darken","plugins.png",3,3,"darken","history.png",4,3,"darken","extensions.png",5,3,"darken","security.png",
6,0,"dark","fcb32.png",7,0,"dark","youtube32.png",8,0,"dark","gpl32.png",9,0,"dark","rate32.png",10];a=0;k=d.i18n.getMessage("menu0").split(";");for(var c=document.createDocumentFragment(),l,e,n,g,v,q,t,u,p,x,r=0;r<f.length;r+=4)t=r/4,n=f[r],q=f[r+1],u=f[r+2],2==n?(g=new Uint8Array(1),crypto.getRandomValues(g),g=g[0]%q.length,t="i"+(t+g),q=q[g],u="i/menu/"+u[g],x=k[f[r+3]+g]):(t="i"+t,u="i/menu/"+u,x=k[f[r+3]]),7>n?(p=0,l=document.createElement("div"),e=document.createElement("div"),v=document.createElement("div"),
g=new Image,q="btn "+q,2<n?(q+=" wide",l.className="btnBoxWide"):l.className="btnBox",e.id=t,e.className=q,g.className="icn",v.className="txt0",g.dataset.url=g.src=u,v.textContent=x,e.appendChild(g),e.appendChild(v),l.appendChild(e),c.appendChild(l)):(n=document.createElement("div"),l=document.createElement("div"),g=new Image,g.src=u,n.id=t,n.className="adt a"+p,g.className="icnm",l.className="txt1",l.textContent=x,n.appendChild(g),e.insertBefore(n,v),e.insertBefore(l,v),p++),a++;h.innerHTML="";h.appendChild(c);
h.style.display="";b.addEventListener("click",z,!1);d.runtime.sendMessage(JSON.stringify({id:20,ga:{ea:"menu"}}))})()}var p,w,d={},m=chrome.runtime.getURL("Gil.html");0!=top.location.href.indexOf(m)&&(top.location.href=m);for(var c in chrome)if("object"==typeof chrome[c]&&(m=Object.getOwnPropertyDescriptor(chrome,c))){d[c]=m.value;m.value={};m.configurable=!1;m.writable=!1;try{Object.defineProperty(chrome,c,m)}catch(A){d[c]=chrome[c]}}"attachShadow"in Element.prototype&&(p=Element.prototype.attachShadow,
Element.prototype.attachShadow=void 0);window.addEventListener("DOMContentLoaded",function(){var d=document.body,c;if(c=p){b:{if(navigator.appVersion&&(c=navigator.appVersion.indexOf("Chrome/"),-1<c)){c=parseInt(navigator.appVersion.slice(c+7));break b}c=0}c=53<c}w=c?p.call(d,{mode:"closed"}):d;y()},!1);window.addEventListener("blur",function(){},!1)})();
